### ISSUE TITLE
How to define cred.js

### ISSUE THREAD

**Issue by scheung38** [DDCreationStudios/fetchingInReact#1]
It is referenced in App.js

import cred from './cred.js';

But maybe for security you didnt uploaded it, how to define one thanks

**Comment by Createdd** [comment]
Hi @scheung38 ,
you can define the structure as you like :) 
I created and exported an object in the cred.js file.  ;) 
Does this help?

**Comment by TatevG** [comment]
Hello @Createdd,
Can you show an example of your defined structure? I am a new one in ReactJS and don't know what structure it should have :(
Thank's:)

**Comment by Createdd** [comment]
Hi @TatevG  this isn't really a React issue. It is about JavaScript in general. have a look at the export examples for ES6 here: https://stackoverflow.com/questions/29844074/es6-export-all-values-from-object
Hope this helps :)

**Comment by TatevG** [comment]
@Createdd thank's :)
